name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  poolName: 'Default'
  buildConfiguration: 'Release'

trigger:
  branches:
    include:
      - master

stages:
  - stage: Build
    displayName: Build package
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: $(poolName)

        steps:
          - checkout: self
            clean: false
            fetchDepth: 1

          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: false
              arguments: './TeamsTalentMgmtApp/src/TeamsTalentMgmtAppV4/TeamsTalentMgmtAppV4.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: true
              displayName: 'Create pipeline artifacts'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: '$(Build.BuildNumber)'
              displayName: 'Publish pipeline artifacts'

  - stage: Deploy
    displayName: Deploy package
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: 'production'
        pool:
          name: $(poolName)
          
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    azureSubscription: 'Igor''s Visual Studio Enterprise with MSDN(6e2e5bf4-277b-4625-99e1-6a86476b69b3)'
                    appType: 'webApp'
                    webAppName: 'talent-app-v4'
                    package: '$(Pipeline.Workspace)/$(Build.BuildNumber)/*.zip'

